version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - keploy-network

  backend:
    build: ./backend
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/appdb
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - keploy-network

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - keploy-network

networks:
  keploy-network:
    external: true

volumes:
  db_data:
