name: Install Keploy CLI
run:
  curl --silent -L https://keploy.io/ent/install.sh | bash

name: Run Keploy Test Suite
run:
  export KEPLOY_API_KEY=${{ secrets.KEPLOY_API_KEY }}
  keploy test-suite --app=4fda4fac-c01f-4e94-a26d-22f71997d39c --base-path https://crud-api-server-python.onrender.com/ --cloud